import { ref } from 'vue';
export const text = ref('');
export const listtitle = ref('');
export const looktitle = ref('');
export const lookbtn = ref('');
export const Dynamicbtn = ref('');
export const Dynamictitle = ref('');
export const recentVideo = ref('');
export const Videotext = ref('');
export const radartitle = ref('');
export const radarbtn = ref('');
export const scenariotitle = ref('');
export const scenariobtn = ref('');
export const rankingtitle = ref('');
export const rankingbtn = ref('');
export const playlist = ref([]);
